### ISSUE TITLE
Add the custom icons in (backend + frontend)

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/StanfordDaily_Mobile#111]
`icon` attribute in the REST API

**Comment by hesyifei** [comment]
Similar to these:

![with Apple Maps](https://user-images.githubusercontent.com/4939421/52009202-3501b500-2487-11e9-881b-24461e5b743a.PNG)
![with Google Maps](https://user-images.githubusercontent.com/4939421/52009203-3501b500-2487-11e9-90c1-29a9a69e860c.PNG)
