### ISSUE TITLE
Clicking on "share" in author page goes to the wrong URL

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/StanfordDaily_Mobile#73]
Such as this:

https://www.stanforddaily.com/?p=0http://stanforddaily.com/?p=0

**Comment by hesyifei** [comment]
It seems that https://www.stanforddaily.com/?author=1001530 is returning a blank page. Normally `?author` should redirect to the author page.

**Comment by epicfaace** [comment]
Good point. It's likely some kind of security feature turned on such as https://www.icontrolwp.com/blog/block-username-fishing-using-author-ids-scans-wordpress-security-basics-series-pt-6/, maybe part of jnews -- we'd need to change this.

**Comment by epicfaace** [comment]
Oh yeah, I believe WPEngine has a default set of plugins that they apply to all sites.
