### ISSUE TITLE
Map layout and setup

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/StanfordDaily_Mobile#78]
https://docs.expo.io/versions/latest/sdk/map-view

Add in the Stanford map.
Center on stanford / your location.
Can't go past Stanford campus

Adding the search bar on top, with the layout from the mockup.

**Comment by aotsai** [comment]
Completed :
Added search bar
Implemented location tracking functionality 

Next steps: 
Fully implement search functionality
Display Stanford region if user is not on campus

Screenshots: 
![img_4445](https://user-images.githubusercontent.com/41077705/51629795-57cb2100-1efd-11e9-9889-73c05ea19088.PNG)
![img_4446](https://user-images.githubusercontent.com/41077705/51629796-57cb2100-1efd-11e9-93aa-bb7002491e2e.PNG)
![img_4447](https://user-images.githubusercontent.com/41077705/51629797-57cb2100-1efd-11e9-83b2-405b4a7fa91f.PNG)
