### ISSUE TITLE
Implement article list

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/StanfordDaily_Mobile#94]
![image](https://user-images.githubusercontent.com/1689183/51630979-4d5e5680-1f00-11e9-9572-2bf86b4f6f87.png)

(Shana will do the popup)

**Comment by epicfaace** [comment]
REST API endpoint: http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations/info/haas_center/1

**Comment by aotsai** [comment]
<img width="368" alt="screen shot 2019-01-30 at 9 24 15 am" src="https://user-images.githubusercontent.com/41077705/52004911-362de480-247d-11e9-9163-87bdb9cb4966.png">
<img width="368" alt="screen shot 2019-01-30 at 9 24 23 am" src="https://user-images.githubusercontent.com/41077705/52004917-38903e80-247d-11e9-9f4c-016125f92ab9.png">
<img width="369" alt="screen shot 2019-01-30 at 9 24 45 am" src="https://user-images.githubusercontent.com/41077705/52004925-3cbc5c00-247d-11e9-9e63-be3d9034cc45.png">

**Comment by aotsai** [comment]
Updates: 
- Create article list popup
- Implement tap-marker-to-reveal
- Follow button 

Next steps: 
- Fetch correct corresponding articles 
- Animate article list popup
- Implement push notifications for follow button
