### ISSUE TITLE
Backend search functionality

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/StanfordDaily_Mobile#95]
Search by text, search by coordinates

**Comment by epicfaace** [comment]
http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations/search?q=Memorial%20Church

so we can extend so that http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations/search?q=Memorial%20Church&category=…
endpoints look like this:
/locations_search?q=abc
/locations/{loc_id}

**Comment by hesyifei** [comment]
Updated:
http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations
http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations?id=1
http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations?id=2&page=3
http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations_search?q=Memorial%20Church

**Comment by epicfaace** [comment]
@hesyifei 
I think you should rename:

http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations?id=2&page=3 --> http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations/2/posts?page=3

http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations_search?q=Memorial%20Church --> http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations?q=Memorial%20Church

http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations/coordinates/37.425608,-122.170691/0.3 --> http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations?coordinates=37.425608,-122.170691/0.3

Lmk if that makes sense why I'm suggesting this rename, or if you have any more suggestions!
